wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.19
    start_time: 1714611010.62583
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.19
      5: 0.13.9
      8:
      - 5
max_tfidf_features:
  desc: null
  value: 5
output_artifact:
  desc: null
  value: random_forest_export
random_seed:
  desc: null
  value: 42
rf_config:
  desc: null
  value: /home/ismail/Project-Build-an-ML-Pipeline-Starter/multirun/2024-05-01/20-50-05/0/rf_config.json
stratify_by:
  desc: null
  value: neighbourhood_group
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
